name: MoreStoneGeneration
version: ${plugin.version}
main: me.JonathanHoffmann.MoreStoneGeneration.Main
api-version: 1.18
description: Configurable different behaviours for Stone formation to make more blocks renewable.